name: Bug Report
description: File a bug report
labels: ['bug', 'triage']

body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 

        ---

        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How can we reproduce it?
      description: Please write us step by step instructions on how we can reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: dropdown
    id: mobile
    attributes:
      label: Which device did this issue occur on?
      description: Did you encounter the bug on mobile, desktop or both?
      options:
        - Mobile
        - Desktop
        - Both
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Anything else you want us to know?
      description: Add any other context about the problem here.
      placeholder: I had spotty internet
    validations:
      required: false
