name: Feature Request
description: Suggest an idea for this project
labels: ['feature', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Before opening a feature request, please search for the wish in the existing issues. 

        ---

        Thank you for taking the time to file a feature request. To address this bug as fast as possible, we need some information.
  - type: textarea
    id: what-happened
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Describe the solution you would like to have.
      description: A clear and concise description of what you want to happen.
      placeholder: When I open the DEX and connect my wallet I would love to see ...
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Anything else you want us to know?
      description: Add any other context about the problem here.
      placeholder: I had spotty internet
    validations:
      required: false
