name: Production Dex UI Pipeline 

on:
  push:
    branches: 
      - main
    tags:
      - 'v*'

env:
  ENV: "prd"
  APP: "dex"
  
jobs:
  main:
    runs-on: ubuntu-latest    
    name: Web build docker
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      
      - name: Set up Docker Buildx
        id: buildx
        # Use the action from the master, as we've seen some inconsistencies with @v1
        # Issue: https://github.com/docker/build-push-action/issues/286
        uses: docker/setup-buildx-action@master
        # Only worked for us with this option on 🤷‍♂️
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-${{ env.ENV }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.ENV }}-buildx

      - name: Log in to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Extract metadata for docker
        if: |
          github.event_name == 'push' ||
          startsWith(github.ref, 'refs/tags/v')
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aeternity/dex-ui
          tags: |
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
            type=ref,event=tag
            type=ref,event=pr
      
      - name: Build and push docker image
        if: |
          github.event_name == 'push' ||
          startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          # Note the mode=max here
          # More: https://github.com/moby/buildkit#--export-cache-options
          # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'synchronize'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - uses: actions/checkout@v2
        with:
          repository: aeternity/gitops-apps.git
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: Get the tag version
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_version
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Production Deploy
        if: startsWith(github.ref, 'refs/tags/v')
        uses: aeternity/ae-github-actions/argocd-deploy@v1
        with:
          url-prefix: ${{ steps.get_version.outputs.TAG }}
          env: ${{ env.ENV }}
          app: ${{ env.APP }}
