name: Local

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: local-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Prettier
        run: npm run format:check
      - name: Unit Tests
        run: npm run test:unit
      - name: E2E Tests
        run: npm run test:e2e -- --headless
